### ISSUE TITLE
Crash when choosing associated repository

### ISSUE THREAD

**Issue by wilkinsona** [nebhale/git-pivotal-tracker-integration#3]
```
git start
1. Alpha
2. Bravo
3. Charlie
Choose project associated with this repository: 3

/Users/awilkinson/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/git-pivotal-tracker-integration-1.1.0/lib/git-pivotal-tracker-  integration/pivotal_configuration.rb:71:in `project_id': undefined method `strip' for 788065:Fixnum (NoMethodError)
    from /Users/awilkinson/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/git-pivotal-tracker-integration-1.1.0/lib/git-pivotal-tracker- integration/base.rb:24:in `initialize'
    from /Users/awilkinson/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/git-pivotal-tracker-integration-1.1.0/lib/git-pivotal-tracker- integration/start.rb:22:in `initialize'
    from /Users/awilkinson/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/git-pivotal-tracker-integration-1.1.0/bin/git-start:5:in `new'
    from /Users/awilkinson/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/git-pivotal-tracker-integration-1.1.0/bin/git-start:5:in `<top (required   )>'
    from /Users/awilkinson/.rbenv/versions/2.0.0-p0/bin/git-start:23:in `load'
    from /Users/awilkinson/.rbenv/versions/2.0.0-p0/bin/git-start:23:in `<main>'    
```

**Comment by nebhale** [comment]
Pretty sure this is fixed in e3fad7a47c2d033d1adeecea2bf4f56cb4ac6003.  Let me know if you are still seeing it after the next release.
